name: Build DBCsync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'build'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: '>=1.20'

      - name: Install dependencies
        run: |
          go mod tidy -C src

      - name: Make build dir
        run: |
          mkdir -p bin

      # Linux
      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -C src -o ../bin/dbcsync-linux
      - uses: actions/upload-artifact@v4
        with:
          name: dbcsync-linux
          path: bin/dbcsync-linux

      # MacOS Intel
      - name: Build MacOS Intel binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -C src -o ../bin/dbcsync-macos-intel
      - uses: actions/upload-artifact@v4
        with:
          name: dbcsync-macos-intel
          path: bin/dbcsync-macos-intel

      # MacOS ARM64
      - name: Build MacOS ARM64 binary
        run: |
          GOOS=darwin GOARCH=arm64 go build -C src -o ../bin/dbcsync-macos-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: dbcsync-macos-arm64
          path: bin/dbcsync-macos-arm64

      # Windows
      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -C src -o ../bin/dbcsync.exe
      - uses: actions/upload-artifact@v4
        with:
          name: dbcsync-windows
          path: bin/dbcsync.exe